name       : libressl-shim
version    : 2.8.0
release    : 4
source     :
    - https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.8.0.tar.gz : af2bba965b06063518eec6f192d411631dfe1d07713760c67c3c29d348789dc3
license    : OpenSSL
component  : binary.compat
summary    : Security override library for linux-steam-integration
description: |
    This library is provided to assist the Solus 'linux-steam-integration'
    project in securing games by forcing them to use an updated version of
    LibreSSL which they may be vendoring in-tree.
emul32     : yes
libsplit   : no
setup      : |
    %configure --disable-static \
               --prefix=/usr \
               --with-openssldir=/etc/ssl
build      : |
    %make
install    : |
    %make_install

    # Forbid using or building against this dude
    rm -rf $installdir/usr/{share,bin,include}
    rm -rf $installdir/%libdir%/pkgconfig
    rm -rf $installdir/etc

    # Rename all libraries and repoint all the links
    pushd $installdir/%libdir%
    for i in *.so*; do
        newName=$(echo "$i" | sed -re 's@lib(.*).so(.*)@lib\1-libressl.so\2@g')
        if [[ -L $i ]]; then
            oldLink=$(basename `realpath $i`)
            newTgt=$(echo "$oldLink" | sed -re 's@lib(.*).so(.*)@lib\1-libressl.so\2@g')
            rm -v $i
            ln -sv $newTgt $newName
        else
            mv -v $i $newName
        fi
    done
    popd

    # LSI intercept library will repoint all intercept requests to "libssl-libressl.so" etc
